// convpng v6.8
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __sprites__
#define __sprites__
#include <stdint.h>

#define heart_width 8
#define heart_height 8
#define heart_size 66
extern uint8_t heart_data[66];
#define heart ((gfx_sprite_t*)heart_data)
#define heart_green_width 8
#define heart_green_height 8
#define heart_green_size 66
extern uint8_t heart_green_data[66];
#define heart_green ((gfx_sprite_t*)heart_green_data)
#define diamond_width 8
#define diamond_height 8
#define diamond_size 66
extern uint8_t diamond_data[66];
#define diamond ((gfx_sprite_t*)diamond_data)
#define diamond_green_width 8
#define diamond_green_height 8
#define diamond_green_size 66
extern uint8_t diamond_green_data[66];
#define diamond_green ((gfx_sprite_t*)diamond_green_data)
#define spade_width 8
#define spade_height 8
#define spade_size 66
extern uint8_t spade_data[66];
#define spade ((gfx_sprite_t*)spade_data)
#define spade_green_width 8
#define spade_green_height 8
#define spade_green_size 66
extern uint8_t spade_green_data[66];
#define spade_green ((gfx_sprite_t*)spade_green_data)
#define clover_width 8
#define clover_height 8
#define clover_size 66
extern uint8_t clover_data[66];
#define clover ((gfx_sprite_t*)clover_data)
#define clover_green_width 8
#define clover_green_height 8
#define clover_green_size 66
extern uint8_t clover_green_data[66];
#define clover_green ((gfx_sprite_t*)clover_green_data)
#define king_width 22
#define king_height 10
#define king_size 222
extern uint8_t king_data[222];
#define king ((gfx_sprite_t*)king_data)
#define queen_width 16
#define queen_height 10
#define queen_size 162
extern uint8_t queen_data[162];
#define queen ((gfx_sprite_t*)queen_data)
#define jack_width 20
#define jack_height 10
#define jack_size 202
extern uint8_t jack_data[202];
#define jack ((gfx_sprite_t*)jack_data)
#define ace_width 14
#define ace_height 13
#define ace_size 184
extern uint8_t ace_data[184];
#define ace ((gfx_sprite_t*)ace_data)
#define back1_width 22
#define back1_height 32
#define back1_size 706
extern uint8_t back1_data[706];
#define back1 ((gfx_sprite_t*)back1_data)
#define back2_width 22
#define back2_height 32
#define back2_size 706
extern uint8_t back2_data[706];
#define back2 ((gfx_sprite_t*)back2_data)
#define back3_width 22
#define back3_height 32
#define back3_size 706
extern uint8_t back3_data[706];
#define back3 ((gfx_sprite_t*)back3_data)
#define back4_width 22
#define back4_height 32
#define back4_size 706
extern uint8_t back4_data[706];
#define back4 ((gfx_sprite_t*)back4_data)
#define back5_width 22
#define back5_height 32
#define back5_size 706
extern uint8_t back5_data[706];
#define back5 ((gfx_sprite_t*)back5_data)
#define back6_width 22
#define back6_height 32
#define back6_size 706
extern uint8_t back6_data[706];
#define back6 ((gfx_sprite_t*)back6_data)
#define sizeof_sprites_pal 512
extern uint16_t sprites_pal[256];

#endif
